### ISSUE TITLE
Document usage of data structure in high level languages

### ISSUE THREAD

**Issue by fnareoh** [prologin/iorgen#11]
In python for example `arbres = [dict(zip(("x", "y"), map(int, input().split()))) for _ in range(m)]`
is not very clear for beginners on how to access the x and y of the "arbres".

**Comment by Zopieux** [comment]
```python
from typing import NamedTuple

class Point(NamedTuple):
    """Documentation."""
    x: int
    y: int

>>> p = Point(10, 20)
>>> p.x
10
>>> p.y
20
>>> p.x = 42
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: can't set attribute

**Comment by remi-dupre** [comment]
\o/

**Comment by remi-dupre** [comment]
Oh, I didn't notice that your message showed that they are not mutable, that could be an issue for some candidates :(

**Comment by Zopieux** [comment]
Yeah, they are immutable. Then you can just use a normal class def, but I would annotate the types in the the constructor.

**Comment by remi-dupre** [comment]
The initial issue from fnareoh was to help candidate to understand how to use a dictionary, I guess that many people using python don't know how classes work, we could do that but add a tiny "usage section" ?

```python
class Arbre:
    """
    Représentation d'un arbre.

    Utilisation: arbre.x, arbre.y
    """
    def __init__(self, x, y):
        self.x = x  # l'abcisse à laquelle est placé l'arbre
        self.y = y  # l'ordonnée à laquelle est placé l'arbre
```

**Comment by Shaac** [comment]
This is a difficult subject.

I made a lot a research before doing the current implementation. First, the non-documented dictionary way, is how metalang did things, so at least there is no regression here from a candidate point of vue.

But I agree the current situation is not good enough, but I do not know how to properly document the usage. I do believe we should keep dictionaries though, because it is the more pythonic way to do things, from what I gathered online.

I had seen NameTuples, but the fact that they are readonly makes them really disliked. Even though I do not thing it would be that of a problem in our specific use cases. But if a candidate might not understand why changing an attribute does not work.

Using a class is good for documentation, but this is not very pythonic.

**Comment by Shaac** [comment]
A possibility would be to make a comment block, describing the format, but then there is also the question of the language (French/English)

**Comment by fnareoh** [comment]
I would think that making a comment, describing the format, would be the easiest thing and potentially the least risky because defining a class might scare some candidates. But I'm not sure about the question of the languages, all other comment about the input are in french right ?

**Comment by remi-dupre** [comment]
Iorgen can output stuff in English or French when it generates sentences for the "Constraints" section. For our usage we write all configuration files in French and use iorgen accordingly.

**Comment by Shaac** [comment]
This is on `master` for python. We can keep this issue open to do something similar to all languages using dictionaries-like objects instead of C-like structs. Or we can consider this is enough.

**Comment by Shaac** [comment]
For Python, once support for python < 3.7 is dropped, we might consider data class https://www.python.org/dev/peps/pep-0557/

**Comment by Shaac** [comment]
> For Python, once support for python < 3.7 is dropped, we might consider data class https://www.python.org/dev/peps/pep-0557/

We should now be able to drop python 3.6 as it reached end of life in December. It seems python 3.7 is both available on Debian 10 and Ubuntu 18.04 which are currently supported by iorgen (although there are very old and should not limit us), so there is nothing holding us back.

So I’ll experiment with data class when I have the time.

**Comment by Shaac** [comment]
Python dataclass are implemented in the `python_dataclass` branch, as well as type annotations. Looking good so far.

**Comment by Shaac** [comment]
The new python generated code is on master and it looks very nice.

I keep this issue open because we still need to add documentation for perl, prolog, ruby, scheme

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/tech/tools/iorgen/-/issues/11
