### ISSUE TITLE
Nodejs input doesn't work anymore

### ISSUE THREAD

**Issue by multun** [prologin/iorgen#13]
```js
fs.readFileSync("/dev/stdin").toString().split("\n")
```
apparently needs to be replaced by

```js
async function readlineSync() {
    return new Promise((resolve, reject) => {
        var content = '';
        process.stdin.resume();
        process.stdin.on('data', (data) => {
            content += data.toString();
        });
        process.stdin.on('end', () => {
            process.stdin.pause();
            resolve(content.split("\n"));
        });
    });
}


async function main() {
    console.log('reading');
    var a = await readlineSync();
    console.log(a)
}

main();
```

... which is asynchronous.

stdin is a socket now, which makes the first solution fail with ENXIO

**Comment by multun** [comment]
For some reason, stdin is a socket during semifinals. I do not know why or how, but I do know it is. And when stdin is a socket, [/dev/stdin doesn't exist](http://www.answers.candoerz.com/question/211741/linux-nuisance-devstdin-doesn39t-work-with-sockets.aspx). According to our local nodejs expert, synchronously polling a socket isn't an easy task with nodejs, the proposed patch (#14) being a reasonable way to accomplish that (the shortest we could find actually).

**Comment by multun** [comment]
Hm I have to try whether 
```js
fs.readFileSync(0).toString().split("\n")
```
works

**Comment by Shaac** [comment]
How can I reproduce the failing behavior?

**Comment by multun** [comment]
```socat tcp-listen:8080,reuseport exec:"node -e \"require('fs').readFileSync('/dev/stdin')\""```
```curl localhost:8080```

**Comment by Shaac** [comment]
I liked the `fs.readFileSync(0).toString().split("\n")`, but sadly it does not work on Debian, which has nodejs v4.8.2.

Maybe the old solution is better?

**Comment by Shaac** [comment]
I retrieved your old commit, and tested successfully on Archlinux, Debian, and prologin.org
I put it on master.
