### ISSUE TITLE
subject-io-stub.md should not be generated by default but through the option --markdown

### ISSUE THREAD

**Issue by Melyodas** [prologin/iorgen#8]
This is not a feature that will be used constantly and therefore should not be imposed.

**Comment by Melyodas** [comment]
Actually it is not that inconvenient now since the name is no longer `subject.md` but I find weird that a markdown is generated when I do `-l cpp`.
So if you want we can close this issue and open a new one that just asks to generate only languages given with `-l` option when it is used.

**Comment by Shaac** [comment]
So I though having a `None` value to the `--markdown` would be a good idea. But I just found out by reading the ticket that it is what I though out 2 years ago…
Anyway, now we can skip markdown generation on master.
